services:
  # Db service config
  mongo:
    image: mongo:6.0
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  # Authentication microservice config
  authentication:
    build:
      context: .
      dockerfile: Dockerfile.authentication
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/challenge
      AUTH_HOST: authentication
      PORT: ${AUTH_PORT}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"

  # 3. Gateway API config
  gateway:
    build:
      context: .
      dockerfile: Dockerfile.gateway
    depends_on:
      - authentication
    environment:
      MONGO_URI: mongodb://mongo:27017/challenge
      AUTH_HOST: authentication
      AUTH_PORT: ${AUTH_PORT}
      PORT: ${GATEWAY_PORT}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"

volumes:
  mongo_data:
